name: Release Java library

on:
  push:
    tags:
      - "v*"

env:
  GITHUB_REF: "${{ github.ref }}"

jobs:
  build_native:
    name: Build depends native library
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Rust environment
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Build project using cargo
        run: cargo build --release
        working-directory: schnorr-musig-c
      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: schnorr-musig-c-lib
          path: schnorr-musig-c/target/release/*musig_c.*
  test:
    name: Test java project
    runs-on: ubuntu-latest
    needs: build_native
    steps:
      - uses: actions/checkout@v2
      - name: Load native libraries
        uses: actions/download-artifact@v2
        with:
          name: schnorr-musig-c-lib
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: mkdir -p ./src/main/resources/natives/linux_64 && cp ./libmusig_c.so ./src/main/resources/natives/linux_64
      - name: Test with Gradle
        run: gradle clean test
  build_and_publish:
    name: Build jar library
    runs-on: ubuntu-latest
    needs: build_native
    steps:
      - name: Query app version number
        id: get_version
        shell: bash
        run: |
          echo "using app version ${GITHUB_REF:11}"
          echo ::set-output name=app::"${GITHUB_REF:11}"
      - uses: actions/checkout@v2
      - name: Load native libraries
        uses: actions/download-artifact@v2
        with:
          name: schnorr-musig-c-lib
      - run: mkdir -p ./src/main/resources/natives/osx_64 && cp ./libmusig_c.dylib ./src/main/resources/natives/osx_64
      - run: mkdir -p ./src/main/resources/natives/osx_32 && cp ./libmusig_c.dylib ./src/main/resources/natives/osx_32
      - run: mkdir -p ./src/main/resources/natives/linux_64 && cp ./libmusig_c.so ./src/main/resources/natives/linux_64
      - run: mkdir -p ./src/main/resources/natives/linux_32 && cp ./libmusig_c.so ./src/main/resources/natives/linux_32
      - run: mkdir -p ./src/main/resources/natives/windows_64 && cp ./musig_c.dll ./src/main/resources/natives/windows_64
      - run: mkdir -p ./src/main/resources/natives/windows_32 && cp ./musig_c.dll ./src/main/resources/natives/windows_32
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: Build with Gradle
        run: gradle build
        env:
          VERSION: ${{ steps.get_version.outputs.APP }}
      - name: Publish package
        run: gradle clean build sign publish
        env:
          VERSION: ${{ steps.get_version.outputs.APP }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PASSPHRASE }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.OSSRH_TOKEN }}
